Repository operator-framework/getting-started, pull requests merged in 2019-09, with the labels that each got.

#42 Delete CRD as well when clean up the operator.
  README.md
Labels: size/XS

#48 Fix broken links - OLM Documentation was replaced by doc
  .gitignore
  README.md
Labels: size/XS

#51 Update README
  README.md
Labels: lgtm, size/XS

#46 Improve getting started information in order to avoid issues as 32
  README.md
Labels: size/L

#54 README.md: note on link versioning
  README.md
Labels: size/S
