Repository operator-framework/getting-started, pull requests merged in 2020-02, with the labels that each got.

#68 update commands
  README.md
Labels: size/XS

#67 Update README.md
  README.md
Labels: lgtm, size/S

#69 README.md: updates for latest SDK CLI changes (v0.15.1)
  README.md
Labels: size/M
